### ISSUE TITLE
Admin Panel Problem

### ISSUE THREAD

**Issue by legiitoftech** [kako0000000/faucet-script#1]
Hello sir, please tell me the admin username and password.
which is the default.

**Comment by kako0000000** [comment]
UserName : admin
Password : adminadmin

**Comment by nikhilbariki332** [comment]
where is the admin page

**Comment by nikhilbariki332** [comment]
website showing limit reached earn tomorrow

**Comment by kako0000000** [comment]
this admin page 
faucetmaster.php
